#! /bin/sh

set -e

output="$1"
shift 1

groups=$(sed -ne \
    's/^struct testcase_t \([a-z0-9]\+\)_tests\[\] = {$/\1/p' \
    "$@")

trap "rm -f '$output.$$'" 0
exec 1> "$output.$$"

printf \
'/* Automatically generated by %s - do not edit
 *
 * This file defines the table of unit test groups.
 */

#include "util.h"
#include "test/tinytest.h"
#include "test/unittest.h"

' $(basename "$0")

for g in $groups; do
    printf 'extern struct testcase_t %s_tests[];\n' "$g"
done

printf '\nconst struct testgroup_t unittest_groups[] = {\n'

for g in $groups; do
    printf '  { "%s/", %s_tests },\n' "$g" "$g"
done

printf '  END_OF_GROUPS\n};\n'

exec 1>&-
mv -f "$output.$$" "$output"
trap "" 0
