#!/bin/bash

VALGRIND=$1

EVENT_NOKQUEUE=yes
export EVENT_NOKQUEUE


CONFIG="modus_operandi/server-vm06-config.conf"

SERVER="./stegotorus --config-file=${CONFIG}"

if [ -n "$VALGRIND" ]
then
valgrind --leak-check=yes  --db-attach=yes --db-command="/usr/bin/gdb %f %p"  --dsymutil=yes --trace-children=no ${SERVER} 2>&1 | tee 
else
${SERVER} 2>&1 | tee 
fi



# --db-attach=yes