#! /bin/sh

set -e

name="$1"
deftag="$2"
ttag="$3"
vtag="$4"
output="$5"
shift 5

modules=$(sed -ne \
    's/'"$deftag"'_DEFINE_MODULE(\([a-zA-Z_][a-zA-Z0-9_]*\),.*$/\1/p' \
    "$@")

trap "rm -f '$output.$$'" 0
exec 1> "$output.$$"

printf \
'/* Automatically generated by %s - do not edit
 *
 * This file defines a table of all supported %ss.
 */

typedef struct %s_vtable %s_vtable;

' $(basename "$0") "$name" "$ttag" "$ttag"

for m in $modules; do
    printf 'extern const %s_vtable %s_%s_vtable;\n' "$ttag" "$vtag" "$m"
done

printf '\nconst %s_vtable *const supported_%ss[] =\n{\n' "$ttag" "$name"

for m in $modules; do
    printf '  &%s_%s_vtable,\n' "$vtag" "$m"
done

printf '  0\n};\n'

exec 1>&-
mv -f "$output.$$" "$output"
trap "" 0
